### PR TITLE
Use UUIDs for transactions

### PR DESCRIPTION
**Pull request by tmatth**
Replaces #7

### CODE REVIEW

**Comment by nustiueudinastea** [comment]
Nice work @tmatth. I hope @notedit can merge it.

**Comment by nustiueudinastea** [comment]
Hey @tmatth, I will be maintaining a separate fork from now on here: https://github.com/Apollo-Systems/janus-go

Doing this because things are moving very slow on this repo and this lib needs all the help it can get. If you wish to do so, add your PR on that repo.

**Comment by cameronelliott** [comment]
This is an awesome find, and a good fix. But maybe a single global 64-bit transaction number source (used with atomic) would have some advantages.
It would mean no new dependencies: github.com/rs/xid
The probability of collisions would be zero instead of the exceedingly small uuid chance
The performance, which is not really important here, would also be higher.

**Comment by cameronelliott** [comment]
I think what this commit is actually revealing, is that there is transaction collisions in the original code when multiple connections are used to the same Janus instance.
I don’t think Janus needs unique transaction IDs at the web socket level, but actually at the Janus  instance level.

**Comment by tmatth** [comment]
> I think what this commit is actually revealing, is that there is transaction collisions in the original code when multiple connections are used to the same Janus instance.
> I don’t think Janus needs unique transaction IDs at the web socket level, but actually at the Janus instance level.

Yes the bug I was fixing was that when loadtesting Janus, test clients had colliding transaction ids (since these were just monotonically increasing integers starting from 0). I think the best way to think of it is that clients are responsible for generating transaction ids that won't collide with their own (or other client's) requests (which you can never really guarantee), but this applies if you're talking to one Janus instance or a cluster of them.

**Comment by tmatth** [comment]
> Nice work @tmatth. I hope @notedit can merge it.

Thanks @nustiueudinastea, it seems like this never got pulled into your fork though?

**Pull request merged**
